name:                hearthstonehs
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/AdituV/b64hs#readme
license:             BSD3
author:              Iris Ward
maintainer:          aditu.venyhandottir@gmail.com
copyright:           2018 Iris Ward
category:            Game
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - cereal
  - cereal-text
  - containers
  - microlens
  - microlens-th
  - text

library:
  source-dirs: src

executables:
  b64hs:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - hearthstonehs
      - base64-bytestring
      - directory
      - exceptions
      - http-conduit
      - mtl
